# Generated by Django 2.2.2 on 2019-06-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('followers_count', models.PositiveIntegerField()),
                ('friends_count', models.PositiveIntegerField()),
                ('favourites_count', models.PositiveIntegerField()),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
    ]
