# Generated by Django 2.2.2 on 2019-06-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetpipe', '0001_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('full_text', models.CharField(max_length=660)),
                ('retweet_count', models.PositiveIntegerField()),
                ('favorite_count', models.PositiveIntegerField()),
                ('fetched_at', models.DateTimeField()),
                ('tweet_url', models.URLField()),
                ('text', models.CharField(max_length=560)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='tweetpipe.User')),
            ],
        ),
    ]
