# Generated by Django 2.2.2 on 2019-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetpipe', '0003_create_followercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=279)),
                ('tweets', models.ManyToManyField(related_name='hashtags', to='tweetpipe.Tweet')),
            ],
        ),
    ]
